# If you are using a dongle, custom ZMK configuration options should go in this
# file. If you are not using a dongle (using the left as central), this file is
# ignored.

# Enable MAC address based BLE device name
# per https://github.com/zmkfirmware/zmk/issues/1668
CONFIG_BT_DEVICE_NAME_DYNAMIC=y
