# If you are using a dongle, custom ZMK configuration options should go in this
# file. If you are not using a dongle (using the left as central), this file is
# ignored.

# Enable MAC address based BLE device name
# per https://github.com/zmkfirmware/zmk/issues/1668
#CONFIG_BT_DEVICE_NAME_DYNAMIC=y
# Maximum chcaracter of the device name
# (Range: 2 to 248)
#CONFIG_BT_DEVICE_NAME_MAX=30
# per https://discord.com/channels/804036937571631124/1326980212340166657/1348886405899882528
CONFIG_ZMK_KEYBOARD_NAME="SliceMK"
CONFIG_ZMK_BLE_KEYBOARD_NAME_MAC=y
